### ISSUE TITLE
Sign in Error

### ISSUE THREAD

**Issue by sre42** [imjacobclark/github-pull-request-notifier-for-chrome#2]
- Notifier prompting multiple error notifications when not signed in
- Sign in button in that notification navigates to Github.com without further fix.

**Comment by sre42** [comment]
<img width="373" alt="screen shot 2016-02-05 at 11 02 30 am" src="https://cloud.githubusercontent.com/assets/6437181/12856191/7e18ac5c-cbf8-11e5-9fa6-6ace7c05b1bc.png">

**Comment by GLMeece** [comment]
Ditto what @Omarasifshaikh reported. I _am_ signed in. I even signed out and back again. Same irritating message over and over.

Fix quickly, or this gets deleted! :unamused:

**Comment by imjacobclark** [comment]
Thanks for reporting the issue, is it possible for you to do a little bit of debugging. 

If you navigate to browser extensions in Chrome, enable developer mode, view the background page for GitHub Notifier, are there any errors? Could you provide a screenshot of this page?

Thanks.

**Comment by GLMeece** [comment]
Here's a mildly truncated version of my log:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 1]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 2]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 3]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 4]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 5]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 1]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 5]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 2]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 3]/pulls 404 (Not Found)
GET https://github.com/[my company name]/https://github.com/[my company name]/[redacted repo 4]/pulls 404 (Not Found)
```

So, what I see here is that the URL is repeated, along with the base repo owner name. Maybe there's a better way to enter these values? I.E., user error (but need better instructions)?

**Comment by GLMeece** [comment]
OK, after looking at the log, and playing around a bit, here's what I've discovered...
- I assumed that _Organisation_ was just a placeholder - of no real consequence.
- I then assumed that _Repo_ was to be a fully-qualified URL to the Repo.

However, it appears that's not the case. It looks like to me that:
- _Organisation_ is the GitHub repo "owner" account (in my case, my company).
- _Repo_ is the raw sub-repo in question.

So - if the base repo owner is **FoobarCo** and the particular repo is **FoobarCo / coolrepo**, then _Organisation_ should be **FoobarCo** and _Repo_ should be **coolrepo**.

Is that correct @imjacobclark ?

If the above is correct, then it is user error. HOWEVER, I believe some instructions to that effect should be included. Also, the error message isn't correct - it's not a login error, it's a "repo specification error" or something to that effect.

**Comment by imjacobclark** [comment]
@GLMeece 

Yes that is correct, so for example, to watch GitHub Notifier, the organisation would be 'imjacobclark' and the repo would be 'github-notifier'. 

I do agree better instructions would be beneficial as I have a couple of bug reports for this issue, or even a better error message, currently I naively assume if there's an error, its due to a sign in problem. 

Thanks for filing the report, I hope you enjoy the extension!

Feel free to submit any PRs for improvements or fixes.

**Comment by sre42** [comment]
hmm, maybe some validation, so that users don't enter in the entire URL in the _Repo_ field (like how @GLMeece  and I did.)

**Comment by imjacobclark** [comment]
@GLMeece @Omarasifshaikh 

Version 1.7 has just shipped with a few features added in around error handling and UI improvements: https://github.com/imjacobclark/github-notifier/releases/tag/1.7

Thanks.

**Comment by sre42** [comment]
Still another repeated error notification. Ill try to fork and look at possible validation fixes, like requireing a user to enter a HTTPS Git link directly. Nice extension btw.

**Comment by imjacobclark** [comment]
I'm going to close this, GitHub notifier should no longer raised error notifications when something goes wrong.

Errors however are still logged in the extensions background console.
