### ISSUE TITLE
Remove rows

### ISSUE THREAD

**Issue by shaunbent** [imjacobclark/github-pull-request-notifier-for-chrome#4]
There doesn't seem to be a way to remove a repository or row once you've added it:

<img width="343" alt="screen shot 2016-02-06 at 11 07 11" src="https://cloud.githubusercontent.com/assets/608566/12866321/18a4be0e-ccc2-11e5-919d-426d484afcf9.png">

Because I've got empty rows just keeps throwing errors:

<img width="375" alt="screen shot 2016-02-06 at 11 08 15" src="https://cloud.githubusercontent.com/assets/608566/12866326/2ec9510e-ccc2-11e5-89bd-a5777a729a49.png">

Maybe I've missed something but I don't think there is a way to do this.

**Comment by imjacobclark** [comment]
Hi @shaunbent,

Yeah, there's no way to remove rows in the UI currently, you can remove the extension, re-install and re-add projects you wish to watch to get around this issue for the time being. 

I'll look into adding removal functionality over the next day or two and hopefully ship a release Monday morning.

**Comment by imjacobclark** [comment]
Shipping https://github.com/imjacobclark/github-notifier/releases/tag/1.7.1 to fix this issue now.

**Comment by imjacobclark** [comment]
@shaunbent 

Remove functionality has been introduced in version 1.8 which I am now shipping (https://github.com/imjacobclark/github-notifier/releases/tag/1.8).

Can this issue now be closed? 

![screen shot 2016-02-07 at 16 09 18](https://cloud.githubusercontent.com/assets/1641689/12873460/2e17744a-cdb5-11e5-8875-2302cede3701.png)

**Comment by shaunbent** [comment]
Nice! Cheers for the update! Looks good! :) close away!
