### ISSUE TITLE
Configurable refresh rate, or try to reduce bandwidth usage overall

### ISSUE THREAD

**Issue by jlogsdon** [imjacobclark/github-pull-request-notifier-for-chrome#5]
I spent some time trying to figure out what part of chrome was using ~200kb of bandwidth every couple of seconds and found out it was this plugin. I only had 5 repositories added, so I was surprised to find this was the culprit.

If there's no way to use the Github API in a more efficient way, at least the refresh rate should be configurable.

edit: At a minimum, call `setTimeout(update, interval)` after each update instead of using `setInterval`. The former will take request and response handling time into account.

**Comment by imjacobclark** [comment]
I think a configurable option for the refresh rate is the best approach for this, and as you suggest, setTimeout. 

I'll take a look at this today/tomorrow.

**Comment by imjacobclark** [comment]
@jlogsdon 

This should be resolved in https://github.com/imjacobclark/github-notifier/releases/tag/1.9.

Could you please verify this works as expected?

**Comment by jlogsdon** [comment]
Works great, thanks.
